version: "3.9"

name: professore-sql

volumes:
  db_data:

networks:
  professore-sql-net:
    driver: bridge

  traefik_proxy:
    external: true

services:
  # 1) WebApp
  web:
    working_dir: /app
    container_name: professore-sql-web

    build:
      context: .
      dockerfile: DockerFile

    environment:
      - FLASK_ENV=${FLASK_ENV}
      - QUERY_DB_HOST=db
      - QUERY_DB_PORT=3306
      - HISTORY_DB_HOST=db
      - HISTORY_DB_PORT=3306
      - QUERY_DB_USER=${QUERY_DB_USER}
      - QUERY_DB_PASSWORD=${QUERY_DB_PASSWORD}
      - QUERY_DB_NAMES=musica,museo,noleggio_auto,aziende # Lista dei database per la lettura
      - HISTORY_DB_USER=${HISTORY_DB_USER}
      - HISTORY_DB_PASSWORD=${HISTORY_DB_PASSWORD}
      - HISTORY_DB_NAME=${HISTORY_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    networks:
      - professore-sql-net
      - traefik_proxy
    labels:
     - "traefik.enable=true"
     - "traefik.http.services.professore-sql.loadbalancer.server.port=5000"

  # 2) Rende gli script .tpl in veri .sql con le variabili del .env
  initdb-renderer:
    image: alpine:3.20
    container_name: professore-sql-renderer
    command: >
      bash -lc '
        set -e;
        apk add --no-cache gettext;
        mkdir -p /init;
        for f in /templates/*.tpl; do
          out="/init/$(basename "$${f%.tpl}")";
          echo "[render] $$f -> $$out";
          envsubst < "$$f" > "$$out";
        done;
        ls -l /init;
      '
    environment:
      - HISTORY_DB_NAME=${HISTORY_DB_NAME}
      - HISTORY_DB_USER=${HISTORY_DB_USER}
      - HISTORY_DB_PASSWORD=${HISTORY_DB_PASSWORD}
      - QUERY_DB_USER=${QUERY_DB_USER}
      - QUERY_DB_PASSWORD=${QUERY_DB_PASSWORD}
    volumes:
      - ./initdb/merged:/init
      - ./initdb/templates:/templates:ro
    networks:
      - professore-sql-net
    restart: "no"

  # 2) Unico MySQL 8.x
  db:
    image: mysql:8.3
    container_name: professore-sql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb/merged:/docker-entrypoint-initdb.d:ro
    depends_on:
      - initdb-renderer
    networks:
      - professore-sql-net
    restart: unless-stopped

  # 3) Unico phpMyAdmin puntato al servizio "db"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: professore-sql-pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # per login come root da pma:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - professore-sql-net
      - traefik_proxy
    restart: unless-stopped
    labels:
     - "traefik.enable=true"
     - "traefik.http.services.professore-sql-admin.loadbalancer.server.port=80"
