version: '3.8'

services:
  # Servizio Flask (web)
  web:
    image: python:3.9
    working_dir: /app
    volumes:
      - .:/app    # Monta la directory di lavoro locale
    command: >
      sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - READ_DB_HOST=${READ_DB_HOST}
      - READ_DB_PORT=${READ_DB_PORT}
      - HISTORY_DB_HOST=${HISTORY_DB_HOST}
      - HISTORY_DB_PORT=${HISTORY_DB_PORT}
      - READ_DB_USER=${READ_DB_USER}
      - READ_DB_PASSWORD=${READ_DB_PASSWORD}
      - READ_DB_NAMES=${READ_DB_NAMES}   # Lista dei database per la lettura
      - HISTORY_DB_USER=${HISTORY_DB_USER}
      - HISTORY_DB_PASSWORD=${HISTORY_DB_PASSWORD}
      - HISTORY_DB_NAME=${HISTORY_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "${APP_PORT}:5000"
    depends_on:
      - db_read
      - db_history
      - phpmyadmin
      - phpmyadmin_read

  # Database per eseguire le query con accesso di sola lettura
  db_read:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db1  # Puoi anche usare questa variabile se necessario
    ports:
      - "${READ_DB_PORT}:3306"    # Porta per il DB di sola lettura
    volumes:
      - db_read_data:/var/lib/mysql

  # Database per la gestione degli utenti e dello storico
  db_history:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${HISTORY_DB_NAME}
    ports:
      - "${HISTORY_DB_PORT}:3306"    # Porta per il DB storico
    volumes:
      - db_history_data:/var/lib/mysql

  # phpMyAdmin per gestire il database di sola lettura
  phpmyadmin_read:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${READ_DB_HOST}
      PMA_PORT: ${READ_DB_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PMA_READ_PORT}:80"    # Porta per accedere a phpMyAdmin

  # phpMyAdmin per gestire il database dello storico
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${HISTORY_DB_HOST}
      PMA_PORT: ${HISTORY_DB_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PMA_HISTORY_PORT}:80"    # Porta per accedere a phpMyAdmin

volumes:
  db_read_data:
  db_history_data:
