version: '3.8'

services:
  # Servizio Flask (web)
  web:
    image: python:3.9
    working_dir: /app
    volumes:
      - .:/app    # Monta la directory di lavoro locale
    command: >
      sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
    environment:
      - FLASK_ENV=development
      - READ_DB_HOST=db_read
      - READ_DB_PORT=3308
      - HISTORY_DB_HOST=db_history
      - HISTORY_DB_PORT=3306
      - READ_DB_USER=readonly_user
      - READ_DB_PASSWORD=readonly_password
      - READ_DB_NAMES=db1,db2,db3   # Lista dei database per la lettura
      - HISTORY_DB_USER=history_user
      - HISTORY_DB_PASSWORD=history_password
      - HISTORY_DB_NAME=history_db
      - SECRET_KEY=mysecretkey
    ports:
      - "5000:5000"    # Porta per l'app Flask
    depends_on:
      - db_read
      - db_history
      - phpmyadmin

  # Database per eseguire le query con accesso di sola lettura
  db_read:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db1
    ports:
      - "3308:3306"    # Porta per il DB di sola lettura
    volumes:
      - db_read_data:/var/lib/mysql

  # Database per la gestione degli utenti e dello storico
  db_history:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: history_db
    ports:
      - "3307:3306"    # Porta per il DB storico
    volumes:
      - db_history_data:/var/lib/mysql

  # phpMyAdmin per gestire i database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db_history
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"    # Porta per accedere a phpMyAdmin
  phpmyadmin_read:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db_read
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"    # Porta per accedere a phpMyAdmin

volumes:
  db_read_data:
  db_history_data:
